travis:
  secure:
    BINSTAR_TOKEN: Q8QYr9KuaAqeE2tFBBDZMuo1vTKJbJImKfSf6BW8mKid542hDnjPf653gT11BWDis0dFmRyKDyZER1wqL1kix4aVB8oFPtPgbheBY2tYxcNw+IEz2JWPo9+98+OcrptMdxGX08KwCqSs2BcDZasXiOF32pvDIaO5smxBlpaUD6C19uuwqCMZ4jZ8Qu9CjRgjOFKvTffwQdyMSKo8m0VuG063YW2Sk80wbeBJ11kKOlzsULRfmVNUGRq67eQRI/UxiokUW1M/GfWLJa6RoQBEivD4aEpkQ9f/4U7F+ZFbpRWlY4SKUNFkCUS9UYAl0DboijXHjO1ARYhDLnM1FNQLD0/tj0MUNzZRGo5MyIJ5cfhFc7ypjAY4fa3BVoxmoNkxV4VgvEKSyJBKySZQFya2W2a/EQoPMN//ZIW5KSUIAjVcJBe+En4d+hlHA1omRrZqL51ek1qJBySI10S00kGepdZFS5821iWrlqW4/wszePNoRnoOlnnpRm810ak6ub9ByvGHRJYwnaudPS9EXI+BpBg87i5GO8Dc1e9Y/L3fPHPvL87Z1URb52z1ZD/cWHbLsHo/Wqyv6RoRvz+/nfZs/MMcVQO+YARdktMAcSZIcnjVpKzg4T+f3WsEb9B3wVXPoZ9p2hXVflRhaMP6D97fTkS7MtRwCso5YHl42lCx8Zw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
